version: "3.8"

services:
  core:
    build:
      context: ../../../
      dockerfile: ./core/Dockerfile
    env_file:
      - .env
    ports:
      - "22000:22000"
    volumes:
      - ../../../core/lute.db:/usr/src/app/core/lute.db
    depends_on:
      - promtail
    networks:
      - lute_network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-config.file=/etc/promtail/config.yaml"]

networks:
  lute_network:
    driver: bridge
    name: lute_network
