[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
async-stream = "0.3.5"
async-trait = "0.1.72"
chrono = { version = "0.4.24", features = ["serde"] }
config = "0.13.3"
console-subscriber = "0.1.9"
data-encoding = "2.4.0"
derive_builder = "0.12.0"
dotenv = "0.15.0"
futures = "0.3.28"
htmlescape = "0.3.1"
kinded = "0.3.0"
lazy_static = "1.4.0"
num-traits = "0.2.16"
opentelemetry = { version = "0.20.0" }
opentelemetry-otlp = { version = "0.13.0" }
ordered-float = "3.7.0"
prost = "0.12.0"
prost-build = "0.12.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.22.0"
rayon = "1.7.0"
regex = "1.8.3"
reqwest = "0.11.18"
reqwest-middleware = "0.2.2"
reqwest-tracing = "0.4.5"
rspotify = "0.12.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
rusqlite_migration = "1.0.2"
rust-s3 = "0.33.0"
rustis = { version = "0.12.0", features = [
  "pool",
  "redis-json",
  "redis-search",
] }
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
serde_urlencoded = "0.7.1"
tl = "0.7.7"
tokio = { version = "1.28.1", features = [
  "rt-multi-thread",
  "macros",
  "tracing",
] }
tokio-retry = "0.3.0"
tonic = "0.10.0"
tonic-reflection = "0.10.0"
tonic-web = "0.10.0"
tracing = "0.1.37"
tracing-opentelemetry = "0.21.0"
tracing-subscriber = { version = "0.3.17", features = [
  "fmt",
  "json",
  "env-filter",
] }
ulid = { version = "1.0.0", features = ["serde"] }
[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5.0", features = [
  'unprefixed_malloc_on_supported_platforms',
] }

[build-dependencies]
tonic-build = "0.10.0"
prost-build = "0.12.0"
