version: "3.8"

services:
  redis:
    image: "redis/redis-stack:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_ARGS=--appendonly yes
    ports:
      - 6379:6379
      - 22001:8001
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  lute_network:
    driver: bridge
